version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: AquaPump
    ports:
      - "8080:8080"
    restart: unless-stopped

networks:
  default:
    driver: bridge
