services:
  app:
    build:
      context: .
      dockerfile: ${APP_DOCKERFILE:-Dockerfile.dev}
      args:
        UID: 1001
        GID: 1001
    ports:
      - "${FRONTEND_HOST_PORT:-8080}:8080"
    user: root
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - vite-cache:/app/node_modules/.vite
    depends_on:
      - server
    networks:
      - aquapump-net

  server:
    build: ./server
    ports:
      - "3001:3001"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - aquapump-net

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - aquapump-net

networks:
  aquapump-net:
    driver: bridge

volumes:
  vite-cache:
