version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        UID: 1001
        GID: 1001
    ports:
      - "${FRONTEND_DEV_PORT:-8081}:8080"
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - vite-cache:/app/node_modules/.vite
    depends_on:
      - server
    networks:
      - aquapump-net

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "${FRONTEND_PROD_PORT:-8080}:8080"
    restart: unless-stopped
    networks:
      - aquapump-net

  server:
    build: ./server
    ports:
      - "3001:3001"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - aquapump-net

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - aquapump-net

networks:
  aquapump-net:
    driver: bridge

volumes:
  vite-cache:

