services:
  frontend:
    build:
      context: ../frontend                 
      dockerfile: Dockerfile  
    ports:
      - "8080:5173"
    volumes:
      - ../frontend/src:/app/src
      - ../frontend/public:/app/public
    environment:
      VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
      VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}

