// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qklycfgxuboktlmbyhba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrbHljZmd4dWJva3RsbWJ5aGJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MzczNjEsImV4cCI6MjA3MzQxMzM2MX0.1KYyOUtH3KJp3TJG4ux4fJaPSHdHKaHvjT7cBtWB7RU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});